### ISSUE TITLE
Tiered 1.19.2.jar is not letting me start minecraft

### ISSUE THREAD

**Issue by Dazzley0001** [Stereowalker/Reforged#41] opened 2023-05-11 00:19 UTC
Hello!

I was looking forward to use this mod, sadly it failed me.
On start I received the Exit-Code 1. I have other mods installed that are working fine.

The file I downloaded is called: Tiered-1.19.2-5.0.3-Forge.jar

I use Curseforge as a Modloader, Gameversion 1.19.2, Forge - 43.2.0.
The modloader works for other mods, so I wonder if it's a problem with the mod itself?

Thanks for helping :3

Sincerely,
Dazzley

**Comment by pumpimpie** [comment] 2023-05-21 10:05
Hi, I know I'm not a developer or anything but I had this same issue with that same version of the mod. Even when I isolated the mod it instantly crashed. For me, it turned out I didn't have UnionLib installed, which is the dependency for Tiered. After I installed that everything worked fine. If you're still having this issue then maybe the same fix will work for you ? I hope !

**Comment by Gavin456b** [comment] 2023-05-21 14:38
Having the same issue, but I have Union Lib and it's still not working

**Comment by pumpimpie** [comment] 2023-05-22 09:31
do you have the correct version of both union lib and the tiered mod for forge? if so then i would say try isolating just those two mods and see if it runs. if it does then the issue is most likely caused by conflict with a different mod, so you would have to figure out which one is causing your game to crash by removing the mods one by one until it works (or vice versa, adding the mods one by one until it crashes). if it still doesn't run even after you've isolated it, then check to make sure you are using the correct version of forge for whatever version of minecraft you're using. and if it still doesn't run then i'm not sure, i'd suggest you open a new issue on this github and post your crash log.

**Comment by Dazzley0001** [comment] 2023-05-22 10:04
> Hi, I know I'm not a developer or anything but I had this same issue with that same version of the mod. Even when I isolated the mod it instantly crashed. For me, it turned out I didn't have UnionLib installed, which is the dependency for Tiered. After I installed that everything worked fine. If you're still having this issue then maybe the same fix will work for you ? I hope !

THIS helped me, thank you!
Nowhere in the description I could read about the needed library. Not even the Minecraft client was telling me!
I used to forget libraries but then at least at the start there would be a message telling me the missing content that I can then download. I hope this message + description will be added in the future :)

**Comment by pumpimpie** [comment] 2023-05-22 16:49
It's no problem, im so glad to help ! and same, it me a while to figure out what the issue was but i checked in the latest.log to see that minecraft instantly crashed without that dependency. i also hope they at least add it to the description in curseforge, hopefully this will help anyone else having the issue :)

**Closed as completed** 2023-05-30 15:50 UTC
